// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjhqidliopjyxcdsgcqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qaHFpZGxpb3BqeXhjZHNnY3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzExNjQsImV4cCI6MjA2ODY0NzE2NH0.4JVVCDHn7W5YTdER51fOp9Ew25HHO_KBu89OnKAor_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});